assessment completed
learn-academy-2022-alpha/week-6-assessment-Valeriano-WebDev pull request #1
Opened 2022-04-04 07:06 UTC by Valeriano-WebDev

2022-04-06 03:27 UTC, SunkissedQueen requested changes
Jacob, I really appreciate what you have been doing on all your assessments. I need you to resubmit the interview questions. Refactor the examples to a different subject matter than what is used in the syllabus. Of course, maintain any terminal commands. These interview questions are your way of showing the great developer I have seen in class and on the assessments. Thanks.

2022-04-06 03:27 UTC, SunkissedQueen commented on code-challenges.test.js
> +/** ReferenceError: capitalizeAndDisplay is not defined **/
thank you for leaving the test suite results

2022-04-06 03:27 UTC, SunkissedQueen commented on code-challenges.test.js
Woohoo

2022-04-06 03:27 UTC, SunkissedQueen commented on code-challenges.test.js
> +})
Doing great on your test structure

2022-04-06 03:27 UTC, SunkissedQueen commented on code-challenges.test.js
> +    let capName = splitName.map((v) => {
It looks like you enjoy clean, concise code. See if you can write this variable without a return and curly braces

2022-04-06 03:27 UTC, SunkissedQueen commented on code-challenges.test.js
> +  let filtered = arr.filter((v) => {
Try writing this variable without curly braces and a return

2022-04-06 03:27 UTC, SunkissedQueen commented on code-challenges.test.js
> +  let cubeElement = arr.reduce((a, v) => {
Try making this a one-liner. I know you can since you got this concept.

2022-04-06 03:27 UTC, SunkissedQueen commented on interview-questions.md
> +Researched answer:
When copying and pasting, please remember to refactor. Since the Cohort has_many: students, we assume Student belongs_to :cohort. Foreign key will live with the belongs_to side. The foreign uses the primary key of the cohort. Therefore, the foreign key is cohort_id: integer. You are definitely correct with the migration.

2022-04-06 03:27 UTC, SunkissedQueen commented on interview-questions.md
> +The Http verb with the url request and passed params defines the correct route
Please refactor using your own example.

2022-04-06 03:27 UTC, SunkissedQueen commented on interview-questions.md
> +action: "GET"    location: /students/new = New method called to display the form for the user to enter data for a new student
What is a unique quality of the new method

2022-04-06 03:27 UTC, SunkissedQueen commented on interview-questions.md
> +action: "GET"    location: /students/2/edit = Edit method to display a form to edit student information with the id of 2.
What is unique about the edit method

2022-04-06 03:27 UTC, SunkissedQueen commented on interview-questions.md
> +   USER STORIES:
These are good starting points for the user experience that helps a developer understand the end goal

2022-04-06 03:27 UTC, SunkissedQueen commented on rails-commenting.rb
You certainly understand what is happening in this controller

2022-04-07 07:14 UTC, Valeriano-WebDev commented
Thank you for all the feedback throughout all the assessments. It has aided me in writing cleaner, more efficient code! I also refactored the interview questions as requested.  I often forget to make them personable and treat them as more of a conversation .

2022-04-07 07:14 UTC, Valeriano-WebDev commented
> 
Thank you for all the feedback throughout all the assessments. It has aided me in writing cleaner, more efficient code! I also refactored the interview questions as requested.  I often forget to make them personable and treat them as more of a conversation .

2022-04-08 16:00 UTC, SunkissedQueen approved these changes
The actual primary key from the cohort model will become the foreign key for the student model.
cohort_id: integer

2022-04-08 16:00 UTC, SunkissedQueen commented on interview-questions.md
> +I forgot to add the foreign key. How can I fix this mistake? What is the name of the foreign key? Would the foreign key be on the
The actual primary key from the cohort model will become the foreign key for the student model. 
cohort_id: integer

2022-04-08 20:00 UTC, merged